// Mock data lấy từ aqualifeplus.vn — dùng cho demo v1
// Sau khi khách approve design → migrate thật từ site cũ

// ─── CATEGORIES ────────────────────────────────────────
export const MOCK_CATEGORIES = [
  {
    id: "he-thong-loc-nuoc",
    name: "Hệ thống lọc nước",
    slug: "he-thong-loc-nuoc",
    description: "Hệ thống lọc nước công nghiệp và đầu nguồn",
    icon: "Droplets",
    productCount: 12,
  },
  {
    id: "may-loc-nuoc",
    name: "Máy lọc nước",
    slug: "may-loc-nuoc",
    description: "Máy lọc nước RO, UF, Nano cho gia đình và doanh nghiệp",
    icon: "Waves",
    productCount: 26,
  },
  {
    id: "thiet-bi-loc-nuoc",
    name: "Thiết bị lọc nước",
    slug: "thiet-bi-loc-nuoc",
    description: "Van, biến áp, thiết bị điều khiển thông minh",
    icon: "Cog",
    productCount: 45,
  },
  {
    id: "loi-loc-nuoc",
    name: "Lõi lọc & Linh kiện",
    slug: "loi-loc-nuoc",
    description: "Lõi lọc chính hãng cho các dòng máy",
    icon: "Filter",
    productCount: 85,
  },
  {
    id: "vat-lieu-loc",
    name: "Vật liệu lọc",
    slug: "vat-lieu-loc",
    description: "Cát, sỏi, than hoạt tính, hạt nhựa",
    icon: "Package",
    productCount: 18,
  },
  {
    id: "dich-vu-bao-tri",
    name: "Dịch vụ bảo trì",
    slug: "dich-vu-bao-tri",
    description: "Bảo trì, thay lõi tận nhà",
    icon: "Wrench",
    productCount: 11,
  },
];

// ─── PRODUCTS ──────────────────────────────────────────
// Ảnh tạm lấy từ website cũ aqualifeplus.vn (khách sở hữu bản quyền)
// Bản chính thức sẽ replace bằng ảnh chụp mới
const OLD_SITE = "https://aqualifeplus.vn/source/storage/app/public/product"

export const MOCK_PRODUCTS = [
  {
    id: "1",
    slug: "may-loc-nuoc-ao-smith-s600",
    name: "Máy lọc nước AO Smith S600",
    excerpt: "Đỉnh cao công nghệ lọc nước tinh khiết với màng RO Side-Stream, giám sát điện tử i-EMS.",
    price: "9.450.000",
    priceOriginal: null,
    category: "may-loc-nuoc",
    categoryName: "Máy lọc nước",
    brand: "AO Smith",
    image: `${OLD_SITE}/238-5-1746588068.png`,
    featured: true,
    badge: "Mới nhất",
  },
  {
    id: "2",
    slug: "may-loc-nuoc-9-cap-sagana",
    name: "Máy lọc nước 9 cấp Sagana",
    excerpt: "Lọc sạch 99.99% tạp chất và vi khuẩn, công nghệ 9 cấp lọc tiên tiến.",
    price: "4.290.000",
    priceOriginal: "5.500.000",
    category: "may-loc-nuoc",
    categoryName: "Máy lọc nước",
    brand: "Sagana",
    image: `${OLD_SITE}/163-1744700869.png`,
    featured: true,
    badge: "Bán chạy",
  },
  {
    id: "3",
    slug: "bo-loc-dau-nguon-uf-5000lh",
    name: "Bộ lọc đầu nguồn UF vỏ Inox 5000L/H",
    excerpt: "Giải pháp lọc nước tổng hiệu quả cho mọi gia đình, công suất 5000L/H.",
    price: "12.500.000",
    priceOriginal: "13.500.000",
    category: "he-thong-loc-nuoc",
    categoryName: "Hệ thống lọc",
    brand: "APLUS",
    image: `${OLD_SITE}/bo-loc-dau-nguon-uf-vo-inox-cong-suat-5000lh-1769415880.png`,
    featured: true,
    badge: "Sale 10%",
  },
  {
    id: "4",
    slug: "karofi-kad-m59-nong-lanh-nguoi",
    name: "Karofi KAD-M59 Nóng - Lạnh - Nguội",
    excerpt: "Giải pháp nước sạch đa năng: nóng, lạnh, nguội tiện lợi.",
    price: "12.900.000",
    priceOriginal: null,
    category: "may-loc-nuoc",
    categoryName: "Máy lọc nước",
    brand: "Karofi",
    image: `${OLD_SITE}/may-loc-nuoc-karofi-kad-m59-1764649392.png`,
    featured: true,
    badge: null,
  },
  {
    id: "5",
    slug: "karofi-kad-n91-voice",
    name: "Karofi KAD-N91 điều khiển giọng nói",
    excerpt: "Máy lọc nước thông minh với 10 lõi lọc Smax và điều khiển giọng nói.",
    price: "16.500.000",
    priceOriginal: null,
    category: "may-loc-nuoc",
    categoryName: "Máy lọc nước",
    brand: "Karofi",
    image: `${OLD_SITE}/may-loc-nuoc-karofi-kad-n91-nong-lanh-1763280937.png`,
    featured: true,
    badge: "Cao cấp",
  },
  {
    id: "6",
    slug: "he-thong-ro-cong-nghiep-500lh",
    name: "Hệ thống RO công nghiệp APLUS 500L/H",
    excerpt: "Phù hợp cho trường học, bệnh viện và các xưởng sản xuất.",
    price: "68.000.000",
    priceOriginal: null,
    category: "he-thong-loc-nuoc",
    categoryName: "Hệ thống lọc",
    brand: "APLUS",
    image: `${OLD_SITE}/kosovota-tong-uf--ban-cong-nghiep-1-1764141321.png`,
    featured: false,
    badge: "Công nghiệp",
  },
  {
    id: "7",
    slug: "van-3-cua-tu-dong-phi-27",
    name: "Van 3 cửa tự động Phi 27 Autovan",
    excerpt: "Van điều khiển thông minh cho hệ thống lọc nước.",
    price: "850.000",
    priceOriginal: null,
    category: "thiet-bi-loc-nuoc",
    categoryName: "Thiết bị lọc",
    brand: "APLUS",
    image: `${OLD_SITE}/van-3-cua-tu-dong-phi-27-1763356603.png`,
    featured: false,
    badge: null,
  },
  {
    id: "8",
    slug: "van-5-cong-f65p1",
    name: "Van 5 cổng tự động F65P1",
    excerpt: "Giải pháp điều khiển hệ thống lọc nước thông minh.",
    price: "1.290.000",
    priceOriginal: null,
    category: "thiet-bi-loc-nuoc",
    categoryName: "Thiết bị lọc",
    brand: "APLUS",
    image: `${OLD_SITE}/van-tu-dong-f65p1-5-nga-1763285913.png`,
    featured: false,
    badge: null,
  },
  {
    id: "9",
    slug: "bien-ap-24v-tw",
    name: "Biến áp 24V TW chính hãng",
    excerpt: "Bộ đổi nguồn máy lọc nước chính hãng, ổn định và bền bỉ.",
    price: "220.000",
    priceOriginal: null,
    category: "thiet-bi-loc-nuoc",
    categoryName: "Thiết bị lọc",
    brand: "TW",
    image: `${OLD_SITE}/bien-ap-24-v-tw-1768964731.png`,
    featured: false,
    badge: null,
  },
  {
    id: "10",
    slug: "dau-bom-tw-tang-ap",
    name: "Đầu bơm TW tăng áp máy lọc RO",
    excerpt: "Giải pháp tăng áp ổn định, bền bỉ cho hệ thống lọc nước RO.",
    price: "890.000",
    priceOriginal: null,
    category: "thiet-bi-loc-nuoc",
    categoryName: "Thiết bị lọc",
    brand: "TW",
    image: `${OLD_SITE}/dau-bom-tw-may-loc-nuoc-1763274128.png`,
    featured: false,
    badge: null,
  },
  {
    id: "11",
    slug: "van-nam-chieu-f64b",
    name: "Van 5 chiều Phi 27 F64B",
    excerpt: "Giải pháp vận hành hệ thống làm mềm nước hiệu quả và bền bỉ.",
    price: "645.000",
    priceOriginal: "795.000",
    category: "thiet-bi-loc-nuoc",
    categoryName: "Thiết bị lọc",
    brand: "APLUS",
    image: `${OLD_SITE}/van-nam-chieu-f64b-phi-27-1763353070.png`,
    featured: false,
    badge: "Sale",
  },
  {
    id: "12",
    slug: "autovalve-f67c1",
    name: "Autovalve F67C1 – Van điều khiển tự động",
    excerpt: "Van điều khiển lọc tự động thông minh, công suất 4 m³/h.",
    price: "1.850.000",
    priceOriginal: null,
    category: "thiet-bi-loc-nuoc",
    categoryName: "Thiết bị lọc",
    brand: "APLUS",
    image: `${OLD_SITE}/autovalve-f67c1-%E2%80%93-van-dieu-khien-loc-tu-dong-thong-minh,-cong-suat-4-m%C2%B3h-1763270895.png`,
    featured: false,
    badge: null,
  },
];

// ─── BLOG POSTS ────────────────────────────────────────
export const MOCK_POSTS = [
  {
    id: "1",
    slug: "su-that-nuoc-dun-soi",
    title: "Sự thật ít ai nói về nước đun sôi: Đun sôi chưa chắc đã là nước sạch",
    excerpt: "Nước đun sôi có thực sự an toàn? Tìm hiểu vì sao đun sôi không loại bỏ kim loại nặng, tạp chất và giải pháp lọc nước hiệu quả bảo vệ sức khỏe gia đình.",
    category: "Kiến thức",
    coverImage: "https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=1200",
    publishedAt: "2026-07-15",
    readingTime: 5,
    author: "APLUS Technologies",
  },
  {
    id: "2",
    slug: "nuoc-ion-kiem-cho-da-day-gout",
    title: "Nước ion kiềm có tốt cho dạ dày và gout không?",
    excerpt: "Nước ion kiềm có giúp cải thiện dạ dày và gout không? Cùng Aplus Technologies tìm hiểu lợi ích, cơ chế hoạt động và cách sử dụng đúng cách.",
    category: "Sức khỏe",
    coverImage: "https://images.unsplash.com/photo-1523362628745-0c100150b504?w=1200",
    publishedAt: "2026-07-08",
    readingTime: 7,
    author: "APLUS Technologies",
  },
  {
    id: "3",
    slug: "loi-chinh-hang-hay-loi-troi-noi",
    title: "Lõi chính hãng hay lõi trôi nổi - Lựa chọn an toàn cho gia đình",
    excerpt: "So sánh lõi lọc nước chính hãng và lõi trôi nổi: rủi ro, lợi ích và giải pháp tiết kiệm bền vững.",
    category: "Hướng dẫn",
    coverImage: "https://images.unsplash.com/photo-1584362917165-526a968579e8?w=1200",
    publishedAt: "2026-06-28",
    readingTime: 6,
    author: "APLUS Technologies",
  },
  {
    id: "4",
    slug: "nuoc-nhiem-clo-tre-so-sinh",
    title: "Nước nhiễm Clo ảnh hưởng thế nào đến trẻ sơ sinh?",
    excerpt: "Tìm hiểu tác hại của Clo trong nước máy đối với trẻ sơ sinh và lý do cần thay lõi lọc nước định kỳ.",
    category: "Sức khỏe",
    coverImage: "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=1200",
    publishedAt: "2026-06-20",
    readingTime: 5,
    author: "APLUS Technologies",
  },
  {
    id: "5",
    slug: "3-sai-lam-may-loc-nuoc-nhanh-hong",
    title: "3 sai lầm khiến máy lọc nước nhanh hỏng dịp Tết",
    excerpt: "3 sai lầm phổ biến khiến máy lọc nước nhanh hỏng. Hướng dẫn kiểm tra, thay lõi và bảo dưỡng đúng cách.",
    category: "Hướng dẫn",
    coverImage: "https://images.unsplash.com/photo-1607443337550-b1d1bef11c3c?w=1200",
    publishedAt: "2026-06-10",
    readingTime: 4,
    author: "APLUS Technologies",
  },
  {
    id: "6",
    slug: "benh-vien-lon-uu-tien-ro",
    title: "Tại sao các bệnh viện lớn ưu tiên lắp đặt hệ thống lọc nước RO?",
    excerpt: "Hệ thống lọc nước RO giúp bệnh viện loại bỏ vi khuẩn, kim loại nặng, clo dư, đảm bảo nguồn nước tinh khiết đạt chuẩn y tế.",
    category: "Công nghiệp",
    coverImage: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1200",
    publishedAt: "2026-05-25",
    readingTime: 8,
    author: "APLUS Technologies",
  },
];

// ─── PROJECTS (Case Studies) ───────────────────────────
// NOTE: coverImage trỏ tới ảnh thật khách gửi (Google Drive).
// Khách tải ảnh về và lưu vào: public/images/projects/ theo đúng tên file bên dưới.
// Bảng ánh xạ đầy đủ (ảnh Drive -> tên file): xem public/images/projects/README.md
export const PROJECT_CATEGORIES = [
  { key: "all", label: "Tất cả" },
  { key: "gia-dinh", label: "Gia đình" },
  { key: "loc-tong", label: "Lọc tổng đầu nguồn" },
  { key: "cong-nghiep", label: "Công nghiệp" },
  { key: "cong-cong", label: "Nước uống công cộng" },
]

export const MOCK_PROJECTS = [
  {
    id: "1",
    slug: "ro-ao-smith-am-tu-bep",
    name: "Lắp đặt máy lọc RO A.O. Smith âm tủ bếp",
    excerpt: "Máy lọc nước RO A.O. Smith lắp gọn dưới bồn rửa, vòi điện tử hiện đại, nước tinh khiết uống trực tiếp.",
    category: "gia-dinh",
    location: "Quy Nhơn, Bình Định",
    client: "Gia đình anh T.",
    coverImage: "/images/projects/duan-ro-aosmith-bep.jpg",
    completedAt: "2026-05",
  },
  {
    id: "2",
    slug: "loc-tong-1-cot-dau-nguon",
    name: "Hệ lọc tổng 1 cột đầu nguồn (bình inox)",
    excerpt: "Cột lọc tổng vỏ inox lắp đầu nguồn, cải thiện nước sinh hoạt cho tắm rửa, giặt giũ toàn bộ ngôi nhà.",
    category: "loc-tong",
    location: "Bình Định",
    client: "Gia đình anh M.",
    coverImage: "/images/projects/duan-loc-tong-1cot.jpg",
    completedAt: "2026-05",
  },
  {
    id: "3",
    slug: "tram-nuoc-uong-cong-cong",
    name: "Trạm nước uống tinh khiết công cộng",
    excerpt: "Trạm cấp nước uống tinh khiết nhiều vòi gắn bảng hiệu APLUS – phục vụ cộng đồng, trường học, khu dân cư.",
    category: "cong-cong",
    location: "Quy Nhơn, Bình Định",
    client: "Dự án cộng đồng",
    coverImage: "/images/projects/duan-tram-nuoc-congcong.jpg",
    completedAt: "2026-04",
  },
  {
    id: "4",
    slug: "loc-tong-3-cot-cong-nghiep",
    name: "Hệ lọc tổng 3 cột composite",
    excerpt: "Hệ thống 3 cột lọc composite kèm van tự động, xử lý nước đầu nguồn quy mô lớn cho nhà xưởng.",
    category: "cong-nghiep",
    location: "Bình Định",
    client: "Doanh nghiệp sản xuất",
    coverImage: "/images/projects/duan-loc-tong-3cot.jpg",
    completedAt: "2026-04",
  },
  {
    id: "5",
    slug: "ro-cong-nghiep-500l",
    name: "Hệ thống RO công nghiệp 500L/h",
    excerpt: "Dây chuyền RO công nghiệp 500L/h với tủ điều khiển, cột tiền lọc – cấp nước tinh khiết ổn định cho sản xuất.",
    category: "cong-nghiep",
    location: "Bình Định",
    client: "Nhà máy sản xuất",
    coverImage: "/images/projects/duan-ro-500l.jpg",
    completedAt: "2026-03",
  },
  {
    id: "6",
    slug: "may-nong-lanh-van-phong",
    name: "Máy lọc nước nóng lạnh cho văn phòng",
    excerpt: "Lắp đặt máy lọc nước nóng lạnh Karofi phục vụ nước uống tiện lợi cho văn phòng, cơ quan.",
    category: "gia-dinh",
    location: "Quy Nhơn, Bình Định",
    client: "Văn phòng doanh nghiệp",
    coverImage: "/images/projects/duan-may-nonglanh-vp.jpg",
    completedAt: "2026-03",
  },
  {
    id: "7",
    slug: "loc-tong-2-cot-composite",
    name: "Hệ lọc tổng 2 cột + cột cải hóa",
    excerpt: "Hệ lọc tổng 2 cột composite kèm cột cải hóa, xử lý nước cứng và cặn cho hộ gia đình quy mô lớn.",
    category: "loc-tong",
    location: "Bình Định",
    client: "Gia đình chị H.",
    coverImage: "/images/projects/duan-loc-tong-2cot.jpg",
    completedAt: "2026-02",
  },
  {
    id: "8",
    slug: "tram-ro-tinh-khiet-3-voi",
    name: "Trạm RO tinh khiết 3 vòi lấy nước",
    excerpt: "Trạm lọc nước RO tinh khiết 3 vòi gắn bảng hiệu APLUS – lắp đặt cho khu vực đông người sử dụng.",
    category: "cong-cong",
    location: "Bình Định",
    client: "Dự án cộng đồng",
    coverImage: "/images/projects/duan-tram-ro-3voi.jpg",
    completedAt: "2026-01",
  },
  {
    id: "9",
    slug: "loi-loc-phuoc-sang-am-tu",
    name: "Bộ lõi lọc Phước Sang lắp âm tủ",
    excerpt: "Cận cảnh bộ lõi lọc thương hiệu Phước Sang lắp gọn gàng dưới bồn rửa – chính hãng, thay dễ dàng.",
    category: "gia-dinh",
    location: "Quy Nhơn, Bình Định",
    client: "Gia đình anh K.",
    coverImage: "/images/projects/duan-loi-phuocsang.jpg",
    completedAt: "2025-12",
  },
];

// ─── SERVICES ──────────────────────────────────────────
export const MOCK_SERVICES = [
  {
    id: "1",
    slug: "khao-sat-nguon-nuoc",
    name: "Khảo sát nguồn nước tận nơi",
    excerpt: "Phân tích chất lượng nước đầu vào và tư vấn giải pháp lọc phù hợp cho từng nguồn nước.",
    icon: "Search",
  },
  {
    id: "2",
    slug: "lap-dat-nhanh-chong",
    name: "Lắp đặt nhanh chóng",
    excerpt: "Đội ngũ kỹ thuật viên tay nghề cao, đảm bảo lắp đặt đúng chuẩn kỹ thuật và thẩm mỹ cao.",
    icon: "Wrench",
  },
  {
    id: "3",
    slug: "bao-tri-dinh-ky",
    name: "Bảo trì định kỳ",
    excerpt: "Chăm sóc, thay lõi lọc, bảo dưỡng hệ thống lọc nước định kỳ, đảm bảo nguồn nước luôn tinh khiết.",
    icon: "Shield",
  },
  {
    id: "4",
    slug: "tra-gop-0-lai-suat",
    name: "Trả góp 0% lãi suất",
    excerpt: "Giải pháp mua máy lọc nước dễ dàng với chính sách trả góp 0% lãi suất, thủ tục nhanh gọn.",
    icon: "CreditCard",
  },
  {
    id: "5",
    slug: "cho-thue-may-loc",
    name: "Cho thuê máy lọc nước",
    excerpt: "Sử dụng máy lọc nước chất lượng cao mà không cần đầu tư ban đầu lớn.",
    icon: "Package",
  },
  {
    id: "6",
    slug: "thay-loi-tan-nha",
    name: "Thay lõi lọc tận nhà",
    excerpt: "Dịch vụ thay lõi lọc tại nhà nhanh chóng với lõi chính hãng đa dạng thương hiệu.",
    icon: "Home",
  },
];

// ─── TESTIMONIALS ──────────────────────────────────────
export const MOCK_TESTIMONIALS = [
  {
    id: "1",
    name: "Chị Ngân",
    role: "Nhân viên ngân hàng",
    content: "Lắp đặt nhanh, gọn, nước trong và sạch hơn hẳn, mình mua cho ba má nên dùng rất yên tâm. Tư vấn nhiệt tình, giá cả hợp lý.",
    avatar: null,
  },
  {
    id: "2",
    name: "Anh Tuấn",
    role: "Chủ shop",
    content: "Chủ shop tư vấn rất tận tâm, giải thích kỹ nên rất yên tâm. Cửa hàng là đại lý chính hãng nên nhìn vào là thấy chuyên nghiệp và đáng tin cậy.",
    avatar: null,
  },
  {
    id: "3",
    name: "Chị Hoa",
    role: "Nhân viên tài chính",
    content: "Vừa sử dụng dịch vụ thay lõi tận nhà, giá cả rất hợp lý, phụ kiện lõi lọc thay đều là hàng chính hãng.",
    avatar: null,
  },
  {
    id: "4",
    name: "Anh Minh",
    role: "Nhân viên văn phòng",
    content: "Nước nhà tôi bị nhiễm phèn nặng, hôi. Lắp hệ thống lọc Aqualife Plus xong, nước trong và hết mùi.",
    avatar: null,
  },
  {
    id: "5",
    name: "Chị Lan",
    role: "Nội trợ",
    content: "Từ khi lắp đặt cột lọc tổng sinh hoạt của Lọc Nước Phước Sang, nước trong nhà tôi trong hơn hẳn.",
    avatar: null,
  },
];

// ─── STATS ─────────────────────────────────────────────
export const MOCK_STATS = [
  { label: "Năm kinh nghiệm", value: "20+" },
  { label: "Khách hàng tin tưởng", value: "3000+" },
  { label: "Đối tác chiến lược", value: "100+" },
  { label: "Dự án lớn hoàn thành", value: "51+" },
];

// ─── USPs ──────────────────────────────────────────────
export const MOCK_USPS = [
  {
    icon: "Headphones",
    title: "Tư vấn miễn phí",
    description: "Hỗ trợ 24/7 tận tâm",
  },
  {
    icon: "Wrench",
    title: "Đơn giản bảo trì",
    description: "Thiết kế module thông minh",
  },
  {
    icon: "TrendingDown",
    title: "Chi phí hợp lý",
    description: "Tiết kiệm ngân sách tối đa",
  },
  {
    icon: "ShieldCheck",
    title: "Chất lượng kiểm chứng",
    description: "Đạt chuẩn quốc tế",
  },
];
